### PR TITLE
Add Bootstrap

### PR DESCRIPTION
**Pull request by leftski**
@dschaub @effron

### CODE REVIEW

**Comment by dschaub** [comment]
For one, I think you need a gem to make bootstrap work, but I'd rather not use bootstrap at all

**Comment by leftski** [comment]
The gem is already installed.

No bootstrap is cool, though.

**Comment by effron** [comment]
should we use bourbon and neat instead?  https://github.com/thoughtbot/neat

**Comment by leftski** [comment]
Dan wants to take a DIY approach to styling.

On Tue, Jun 2, 2015 at 1:53 PM, Harris Effron notifications@github.com
wrote:

> should we use bourbon and neat instead? https://github.com/thoughtbot/neat
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dschaub/sidespin/pull/3#issuecomment-108030257.

## 

[image: Betterment]_Matt Salefski_
Product Manager at Betterment.com http://betterment.com/

**Comment by dschaub** [comment]
bourbon and neat look interesting, are they just for grids? the reason I don't like bootstrap is because it pollutes the global namespace with defaults for everything, and on super common class names (like "label"). grids are the annoying part in CSS, so i'd be down to use something that just handles those

**Pull request closed without merging**
